### ISSUE TITLE
Progress bar and timer stay at 0 when slowing down a video

### ISSUE THREAD

**Issue by maxdrash** [exeldro/obs-media-controls#12]
Hi @exeldro 

One issue here:
OBS 25.0.8, media controls 0.2.2
Ubuntu 20.04
Play video with a slow speed rate.
See media controls timing and progress bar won't move.

Thank you for your great work !

**Comment by exeldro** [comment]
Do you see times next to the progress bar or are they 0?

**Comment by maxdrash** [comment]
The progress bar don't move and timer stay at 00:00 on the left but video stills playing (50% slower for this example).

![image](https://user-images.githubusercontent.com/17526713/93661017-c0f99380-fa54-11ea-81f9-ac13f479f423.png)

**Comment by exeldro** [comment]
This should be fixed with OBS version 26
