### ISSUE TITLE
Hiding individual/looping media sources

### ISSUE THREAD

**Issue by Wiethoofd** [exeldro/obs-media-controls#13]
I have some looping video files as background in various scenes, these show up in the list of controllable media but can't currently be hidden. It's either 'all sources' or 'sources in the selected scene'.

The Audio mixer allows for hiding individual meters, same functionality would be appreciated for the media controls, or at least a toggle to hide media which is set to loop.

**Comment by veremenko-y** [comment]
yes please!

**Comment by exeldro** [comment]
Added in version 0.4.0
