### ISSUE TITLE
Not showing up in OBS Mac OS X 10.15.7 OBS 26.1.0 (64bit)

### ISSUE THREAD

**Issue by charlyhotel** [exeldro/obs-media-controls#15]
Thank you for making this available.

Unfortunately the controls do not show up anywhere - i cannot find them under 'docks' or anywhere else.

Being on a Mac i just used the installer provided at obsproject.com.

OBS was shut down during installer run.

Other of your extensions - most notably move transition - install and work great btw.

I don't have any idea where which files would have to go if i tried to move them there by hand - also, i do not have the contents of the installer as separate files...sorry, just being a user.

Is there something i can do - apart from running the installer a couple of times again?

**Comment by statik** [comment]
I made this script and it fixed the issue on my macbook. I will prepare a pull request for this plugin to fix the issue in the build.

```
#!/usr/bin/env bash

PLUGIN='/Library/Application Support/obs-studio/plugins/media-controls/bin/media-controls.so'
OLD_PATH_PREFIX='/tmp/obsdeps/lib'
NEW_PATH_PREFIX='@executable_path/../Frameworks'
QT_WIDGETS='QtWidgets.framework/Versions/5/QtWidgets'
QT_GUI='QtGui.framework/Versions/5/QtGui'
QT_CORE='QtCore.framework/Versions/5/QtCore'


if ! otool -l "${PLUGIN}" | grep -q "${OLD_PATH_PREFIX}"; then
  echo "Old paths not found, nothing to do."
  exit 0
fi

echo "Found $OLD_PATH_PREFIX entries inside $PLUGIN, patching"

install_name_tool \
  -change "${OLD_PATH_PREFIX}/${QT_WIDGETS}" "${NEW_PATH_PREFIX}/${QT_WIDGETS}" \
  -change "${OLD_PATH_PREFIX}/${QT_GUI}" "${NEW_PATH_PREFIX}/${QT_GUI}" \
  -change "${OLD_PATH_PREFIX}/${QT_CORE}" "${NEW_PATH_PREFIX}/${QT_CORE}" \
  "${PLUGIN}"
```
