### ISSUE TITLE
Install errors on Mac OSX 10.15.5

### ISSUE THREAD

**Issue by PhilRowe** [exeldro/obs-media-controls#2]
Hello! very excited to try out this plugin but its not working on my Mac at the moment. Installation ran fine however the new dock was not showing in the view -> dock menu. Initial message in obs logs showed:

12:47:24.348:   Referenced from: /Library/Application Support/obs-studio/plugins/media-controls/bin/media-controls.so
12:47:24.348:   Reason: image not found
12:47:24.348: 
12:47:24.349: Module '/Library/Application Support/obs-studio/plugins/media-controls/bin/media-controls.so' not loaded

I tried copying the media controls plugin from /Library/Application Support/obs-studio/plugins/media-controls to /Users/philiprowe/Library/Application Support/obs-studio/plugins/media-controls and then started receiving the following error message:

13:24:31.575: os_dlopen(/Users/philiprowe/Library/Application Support/obs-studio/plugins/media-controls/bin/media-controls.so->/Users/philiprowe/Library/Application Support/obs-studio/plugins/media-controls/bin/media-controls.so): dlopen(/Users/philiprowe/Library/Application Support/obs-studio/plugins/media-controls/bin/media-controls.so, 257): Library not loaded: /usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets
13:24:31.575:   Referenced from: /Users/philiprowe/Library/Application Support/obs-studio/plugins/media-controls/bin/media-controls.so
13:24:31.575:   Reason: image not found

I then tried installing qt5 framework via brew and OBS failed to launch, no errors were shown in the logs relating to the crash.

**Comment by Jamie-** [comment]
Also just tried to install this on Mac and getting the same issue with the same errors. I haven't tried to install Qt etc though, just followed the instructions on OBS forum.

**Comment by Jamie-** [comment]
I compiled OBS from source with this plugin as documented in the README and it does appear in the Docks menu and I can open it up just fine.

<img width="479" alt="Screenshot 2020-07-19 at 18 26 12" src="https://user-images.githubusercontent.com/4096784/87880922-8db36d80-c9ed-11ea-8fdf-7f4bd0b14f2b.png">

However, the icons don't work properly and none of the buttons in the entire application are clickable (the timeline slider works great). Though I don't think the button clicking problem is related to this plugin. I need to do some more investigation.

**Comment by ucomesdag** [comment]
The library is not static linked, and thus needs to be distributed with the Qt Framework. Or find some one that can zip the /usr/local/opt/qt/ folder or just statically link it. Same for the media buttons because of the missing font.

**Comment by NReilingh** [comment]
If you get an error upon launch after installing the relinked .so, just open up Security & Privacy in System Preferences, General tab, and you should see a warning about the file with an "Allow" button that you can click.

**Comment by mrgroen** [comment]
Thanks i needed this! 😄

**Comment by exeldro** [comment]
@ucomesdag so I could add those lines to https://github.com/exeldro/obs-media-controls/blob/master/.github/workflows/build.yml to make correct Mac builds?

**Comment by ucomesdag** [comment]
> @ucomesdag so I could add those lines to https://github.com/exeldro/obs-media-controls/blob/master/.github/workflows/build.yml to make correct Mac builds?
> 

Yes, that should work. Ideally when the whole thing is build statically it should all link to the same included framework.

**Comment by exeldro** [comment]
Fixed by #5
