### ISSUE TITLE
Can crash obs by stopping empty Media Source

### ISSUE THREAD

**Issue by geslotencirkel** [exeldro/obs-media-controls#8]
If a media source isn't assigned, it still shows up in the controls, and you can crash OBS by pressing stop and other controls repeatedly

**Comment by exeldro** [comment]
can you add a crashlog?

**Comment by geslotencirkel** [comment]
hope this is enough

Unhandled exception: c0000005
Date/Time: 2020-08-20, 19:43:31
Fault address: 53342B36 (e:\obs-studio-21.1.2-full\bin\32bit\w32-pthreads.dll)
libobs version: 25.0.8 (32-bit)

Thread E28 (Crashed)
Stack    EIP      Arg0     Arg1     Arg2     Arg3     Address
00A9C00C 53342B36 11F1A718 24399930 1242FDC0 00A9C03C w32-pthreads.dll!pthread_mutex_unlock+0x16
00A9C020 0F04CF0A 11F1A3E0 00000001 00A9C050 513F5E2C obs-ffmpeg.dll!mp_media_play_pause+0x3a
00A9C034 0F04933E 11F1A3E0 00000001 24399930 00A9C0F4 obs-ffmpeg.dll!ffmpeg_source_play_pause+0xe
00A9C044 513F5E2C 1242FDC0 00000001 24465490 01A92FD2 obs.dll!obs_source_media_play_pause+0x3c
00A9C058 50014402 24399930 00000000 00000001 00A9C130 media-controls.dll!MediaControl::on_playPauseButton_clicked+0x32
00A9C068 01A92FD2 24504420 01D9D24C 01D9D24C 00A9C130 qt5core.dll!0x1a92fd2
00A9C0FC 01A931EE 24504420 013AD870 00000002 00A9C130 qt5core.dll!0x1a931ee
00A9C110 0119DC10 23F2B130 24504420 00A9CA70 23F2B101 qt5widgets.dll!0x119dc10
00A9C13C 0119DB6C 00000000 00000000 00000000 00000000 qt5widgets.dll!0x119db6c

**Comment by exeldro** [comment]
Version 26 of OBS fixes it.
